---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test

workflows:
  version: 2
  tests:
    jobs:
      - build
  scheduled:
    jobs:
      - build
    triggers:
      - schedule:
         cron: "8 9 * * *"
         filters:
           branches:
             only:
               - master

